services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: vlrbettingbot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"

  redis:
    image: redis:6
    restart: always
    ports:
      - "6379:6379"

  scraper:
    build: ./scraper
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    env_file:
      - .env

  bot:
    build: ./bot
    depends_on:
      - db
      - scraper
      - redis
    env_file:
      - .env
